on:
  push:
    branches:
      - main

jobs:
  release-drafter:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@6df64e4ba4842c203c604c1f45246c5863410adb # tag=v5
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}